### ISSUE TITLE
Publish to NPM

### ISSUE THREAD

**Issue by jooola** [directus/gatsby-source#5]
We need to publish this project to NPM in order for people to start using it, even if it isn't tested yet.

The current name collide with the existing `gastby-source-directus` package, but I suggested we use the `@directus` namespace, and push this project under `@directus/gatsby-source-directus`.

The process should be done in the Github actions, this allow us to use secret tokens without having to know them.

Here is a sample from https://github.com/actions/setup-node on how to do that using CI.
```
steps:
- uses: actions/checkout@v1
- uses: actions/setup-node@v1
  with:
    node-version: '10.x'
    registry-url: 'https://registry.npmjs.org'
- run: npm install
- run: npm publish
  env:
    NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
```

We need  @rijkvanzanten or @benhaynes to approve and set a NPM_TOKEN in the Github Actions variables so we can set this up.
